# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maingui.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(650, 820)
        MainWindow.setMinimumSize(QtCore.QSize(650, 820))
        MainWindow.setMaximumSize(QtCore.QSize(650, 820))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 231, 121))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 160, 73))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.radio_toad = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_toad.setObjectName("radio_toad")
        self.gridLayout.addWidget(self.radio_toad, 0, 0, 1, 1)
        self.radio_glider_gun = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_glider_gun.setObjectName("radio_glider_gun")
        self.gridLayout.addWidget(self.radio_glider_gun, 0, 1, 1, 1)
        self.radio_beacon = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_beacon.setObjectName("radio_beacon")
        self.gridLayout.addWidget(self.radio_beacon, 1, 0, 1, 1)
        self.radio_life_spaceship = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_life_spaceship.setObjectName("radio_life_spaceship")
        self.gridLayout.addWidget(self.radio_life_spaceship, 1, 1, 1, 1)
        self.radio_glider = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_glider.setObjectName("radio_glider")
        self.gridLayout.addWidget(self.radio_glider, 2, 0, 1, 1)
        self.radio_pentomino = QtWidgets.QRadioButton(self.layoutWidget)
        self.radio_pentomino.setObjectName("radio_pentomino")
        self.gridLayout.addWidget(self.radio_pentomino, 2, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 0, 141, 121))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 20, 77, 83))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.button_start = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_start.setObjectName("button_start")
        self.verticalLayout_3.addWidget(self.button_start)
        self.button_pause = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_pause.setObjectName("button_pause")
        self.verticalLayout_3.addWidget(self.button_pause)
        self.button_stop = QtWidgets.QPushButton(self.layoutWidget1)
        self.button_stop.setObjectName("button_stop")
        self.verticalLayout_3.addWidget(self.button_stop)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 130, 620, 630))
        self.groupBox_3.setMinimumSize(QtCore.QSize(620, 630))
        self.groupBox_3.setMaximumSize(QtCore.QSize(620, 630))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.surface = QtWidgets.QGraphicsView(self.groupBox_3)
        self.surface.setGeometry(QtCore.QRect(7, 7, 605, 605))
        self.surface.setMinimumSize(QtCore.QSize(605, 605))
        self.surface.setMaximumSize(QtCore.QSize(605, 605))
        self.surface.setObjectName("surface")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 650, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radio_toad.setText(_translate("MainWindow", "Toad"))
        self.radio_glider_gun.setText(_translate("MainWindow", "Glider gun"))
        self.radio_beacon.setText(_translate("MainWindow", "Beacon"))
        self.radio_life_spaceship.setText(_translate("MainWindow", "Life spaceship"))
        self.radio_glider.setText(_translate("MainWindow", "Glider"))
        self.radio_pentomino.setText(_translate("MainWindow", "Pentomino"))
        self.button_start.setText(_translate("MainWindow", "Start"))
        self.button_pause.setText(_translate("MainWindow", "Pause"))
        self.button_stop.setText(_translate("MainWindow", "Stop"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

